### ISSUE TITLE
Python3 dependency

### ISSUE THREAD

**Issue by leventyalcin** [NorfairKing/super-user-stone#2]
As you know there is no mainstream distro which comes with Python3 pre-installed. I'm not a Python developer and don't develop something in Python. I'm not sure I'd want to install Python3 just use super-user-stone. At the same time most of OSes have Python 2.7 by default (Debian, Ubuntu, CentOS, MacOSX)

**Comment by NorfairKing** [comment]
This started out as a dumb little project that I made because I needed it.
I figured that I wouldn't ever want to rewrite it just because python2 wasn't standard anymore. I assumed that anyone who uses dotfiles to the point where they need the Super User Stone, they would definitly have Python3.
I want to thank you for pointing this out, but as python3 is less than 100MB in size, I don't think I will be rewriting this just to make it work with python 2.7.

Lastly, I want to point out that python3 _is_ standard on the distro I'm using (arch linux).
